#!/bin/bash
###### PREPARE NEW PC FOR WORK ################################################
### 1. install basic tools manually
#sudo apt-get install -y vim git xclip

### 2. Then setup git to use ssh keys
## https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

## 2a. Create an ssh key (use a passphrase)
#ssh-keygen -t rsa -b 4096 -C "teve@tdc.dk"

## 2b. Add key to ssh agent
#eval "$(ssh-agent -s)"

## 2c. Add the ssh key to the ssh-agent
#ssh-add ~/.ssh/id_rsa

### 3. Add the ssh-key to my github account
# https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

## 3a. Copy the public key
#xclip -sel clip < ~/.ssh/id_rsa.pub

## 3b. Create a new ssh-key on github
# https://github.com/settings/keys
###############################################################################

# TODO
# FIX Clashing shortcuts between default ubuntu and PyCharm (intellij IDE's)
# https://askubuntu.com/questions/412046/unable-to-use-intellij-idea-keyboard-shortcuts-on-ubuntu
# https://superuser.com/questions/358749/how-to-disable-ctrlshiftu-in-ubuntu-linux




### Synaptics trackpad setings
# Interesting Articles
#    http://lukeluo.blogspot.dk/2014/04/mac-book-pro-113-linux-customization-5.html
#    https://www.x.org/archive/X11R7.5/doc/man/man4/synaptics.4.html

if [[ $(sudo lshw 2>&1 | grep "version: ThinkPad L450" | wc -l) = '1' ]]; then
    echo "Configuring synaptics on ThinkPad L450"
    synclient VertScrollDelta=-200   # default -114
    synclient HorizScrollDelta=-200  # default -114
    synclient PalmDetect=1           # default 0 (need long time testing to tune the other palm* values)
    synclient FingerHigh=40          # default 30
    synclient FingerLow=35           # default 25
    # Mouse movement
    synclient AccelFactor=0.03       # default 0.0348918
    synclient MinSpeed=1             # default 1
    synclient MaxSpeed=1.75          # default 1.75
    # Scroll after release
    synclient CoastingSpeed=20       # default 20
    synclient CoastingFriction=50   # default 50
fi


# PREPARE
sudo apt-get update

### INSTALL PROGRAMS #########################################################
# System tools
sudo apt-get -y install \
	dconf-editor	\
	unity-tweak-tool\
	gparted		\
	smartmontools	\
	numlockx	\
	openssh-server	\
	tree		\
	iotop		\
	htop		\
	compizconfig-settings-manager	\
	tmux		\
	curl		\

# General apps
sudo apt-get -y install \
	wireshark 	\
	virtualbox	\
	meld            \



# Python development
sudo apt-get -y install	\
	python-pip	\


pip install virtualenv
pip install --upgrade pip



# Krusader and it's dependencies
sudo apt-get -y install \
	krusader	\
	khelpcenter	\
	kde-baseapps-bin\
	kdiff3		\
	krename		\
	unrar		\
	rar		\
	

### CONFIGURE UI #############################################################
# Move menu's to the app itself 
dconf write /com/canonical/unity/integrated-menus true			

# Always show the menu
dconf write /com/canonical/unity/always-show-menus true

# Enable 2x2 workspace layout		
dconf write /org/compiz/profiles/unity/plugins/core/hsize 2		
dconf write /org/compiz/profiles/unity/plugins/core/vsize 2

# Trackpad scroll like my Mac :-)
dconf write /org/gnome/desktop/peripherals/touchpad/natural-scroll true


# Format date/time in menubar
dconf write /com/canonical/indicator/datetime/time-format "'custom'"
dconf write /com/canonical/indicator/datetime/show-week-numbers true
dconf write /com/canonical/indicator/datetime/custom-time-format "'%A %d/%m-%Y   %H:%M:%S'"

# Battery
dconf write /com/canonical/indicator/power/show-time true


### TODO freeplane 1.6.6 (apt-get only provides 1.3.15-3)
	# Make curl/wget dl + install
	# Source: https://www.freeplane.org/wiki/index.php/Ubuntu
	# download https://sourceforge.net/projects/freeplane/files/freeplane%20stable/freeplane_1.6.6%7Eupstream-1_all.deb/download
	# Install:  sudo dpkg -i freeplane_1.6.6~upstream-1_all.deb
	# Unpacks over existing old version



# TODO: post script or guide to add current user to a wireshark group

# for git
# git config --global user.email "teve@tdc.dk"
# git config --global user.name  "Thomas von Eyben"
# git 2.0 change - restore old behavior:
# 	git config --global push.default matching

